ecommerce/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    path("", views.index, name='index'),
    # cart
    path("cart/", views.cart_list, name='cart-list'),
    path('cart/add/<int:item_id>/', views.add_to_cart, name='add-to-cart'),
    path('cart/increase/<int:item_id>/', views.increase_quantity, name='increase-quantity'),
    path('cart/remove/<int:item_id>/', views.decrease_quantity, name='decrease-quantity'),
    path('cart/delete/<int:item_id>/', views.remove_item, name='remove-item'),
    
    # search
    path('search/', views.search, name='search'),
    
    # items
    path("items/", views.item_list, name='item-list'),
    path("items/<int:item_id>/", views.item_detail, name='item-detail'),
    path('items/<str:category>/', views.item_category, name='item-list'),
    path("items/<int:item_id>/review", views.create_review, name='create-review'),
    path("items/<int:review_id>/edit/", views.ReviewUpdateView.as_view(), name='review-update'),
    path("items/<int:review_id>/delete/", views.ReviewDeleteView.as_view(), name='review-delete'),
    
    # order
    path('order/', views.order_form, name='order-form'),
    path('order/payment/', views.process_payment, name='process_payment'),
    path('order/payment/success/', TemplateView.as_view(template_name="success.html"), name='payment_success'),
    path('order/payment/failed/', TemplateView.as_view(template_name="failed.html"), name='payment_failed'),
    
    # etc
    path("profile/<int:user_id>/", views.user_profile, name='user-profile'),
]

ecommerce_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from ecommerce.views import CustomPasswordChangeView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # admin
    path('admin/', admin.site.urls),

    # ecommerce
    path('', include("ecommerce.urls")),

    # allauth
    path(
        "email-confirmation-done/",
        TemplateView.as_view(template_name="ecommerce/email.confirmation_done.html"),
        name="account_email_confirmation_done"),
    path('password/change/',
        CustomPasswordChangeView.as_view(),
        name="account_password_change",
        ),
    path('', include("allauth.urls")), # for sign in, sign up, etc
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django_countries.fields import CountryField
from .validators import *

class User(AbstractUser):
    firstName = models.CharField(max_length=15, validators=[validate_no_numbers, validate_no_special_characters])
    lastName = models.CharField(max_length=15, validators=[validate_no_numbers, validate_no_special_characters])
    nickname = models.CharField(
        max_length=15, 
        unique=True, 
        null=True,
        validators=[validate_no_special_characters],
        error_messages={
            "unique": "A user is already registered with this nickname."
        }
    )
    address = models.CharField(max_length=15, validators=[validate_no_special_characters])
    city = models.CharField(max_length=15, validators=[validate_no_special_characters, validate_no_numbers])
    country = CountryField(blank_label='(select country)')
    province = models.CharField(max_length=2, validators=[validate_no_special_characters, validate_no_numbers])
    postalCode = models.CharField(max_length=6, validators=[validate_postal_code])
    history = models.TextField(blank=True, null=True)
    createdAt = models.DateTimeField(verbose_name="Date Created", auto_now_add=True, null=True)

    def __str__(self):
        return self.email


class Item(models.Model):
    name = models.CharField(max_length=15)
    category = models.CharField(max_length=15)
    available = models.BooleanField(default=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='items/images/', blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='items', null=True, blank=True)
    
    def __str__(self):
        return self.name


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    firstName = models.CharField(max_length=15, validators=[validate_no_numbers, validate_no_special_characters])
    lastName = models.CharField(max_length=15, validators=[validate_no_numbers, validate_no_special_characters])
    email = models.EmailField()
    address = models.CharField(max_length=15, validators=[validate_no_special_characters])
    city = models.CharField(max_length=15, validators=[validate_no_numbers, validate_no_special_characters])
    country = CountryField(blank_label='(select country)', null=False)
    province = models.CharField(max_length=2, validators=[validate_no_special_characters, validate_no_numbers])
    postalCode = models.CharField(max_length=6, validators=[validate_postal_code])
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)
    is_paid = models.BooleanField(default=False)
    paymentId = models.CharField(max_length=15, blank=True, null=True)

    def __str__(self):
        return f'Order {self.id} by {self.firstName} {self.lastName}'
    
    def get_total_price(self):
        return sum(item.price * item.quantity for item in self.order_items.all())

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_items')
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='order_items')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f'{self.item.name} (x{self.quantity})'


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='carts')
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Cart for {self.user.email}'


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='cart_items')
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='cart_items')
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'{self.item.name} (x{self.quantity})'

class Review(models.Model):
    rate = models.PositiveIntegerField()
    comment = models.TextField()
    createdAt = models.DateTimeField(auto_now_add=True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reviews')

    def __str__(self):
        return f'Review by {self.user.email} for {self.item.name}'

ecommerce/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from allauth.account.views import PasswordChangeView
from django.contrib.auth.decorators import login_required
import stripe
from django.views.generic import UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.conf import settings

from .models import User, Item, Order, OrderItem, Cart, CartItem, Review
from .forms import ReviewForm, OrderForm, PaymentForm, SignupForm

# get sum of review rate / number of reviews
def review_avg():
    items = Item.objects.all()
    reviews = Review.objects.all()

    review_sum = {}
    review_num = {}
    review_avg = {}
    
    for item in items:
        review_sum[item.id] = 0 
        review_num[item.id] = 0 
    
    for review in reviews:
        review_sum[review.item.id] += review.rate
        review_num[review.item.id] += 1

    for key in review_sum:
        try:
            review_avg[key] = float(review_sum[key]) / float(review_num[key])
        except:
            review_avg[key] = 0

    return review_avg


def index(request):
    items = Item.objects.all()
    reviews = Review.objects.all()

    context = {
        "items": items,
        "reviews": reviews,
        "review_avg": review_avg()
        }
    return render(request, "ecommerce/index.html", context)


# password change view
class CustomPasswordChangeView(PasswordChangeView):
    def get_success_url(self):
        return reverse("index")


# ==================== items views ====================
def item_list(request):
    items = Item.objects.all()
    reviews = Review.objects.all()

    context = {
        "items": items,
        "reviews": reviews,
        "review_avg": review_avg()
        }
    return render(request, "ecommerce/item_list_templates/item_list.html", context)


def item_detail(request, item_id):
    item = Item.objects.get(id=item_id)
    reviews = Review.objects.filter(item=item)
    is_reviewed = reviews.filter(user=request.user).exists() if request.user.is_authenticated else False
    my_review = reviews.filter(user=request.user).first() if is_reviewed else ""

    context = {
        "item": item,
        "reviews": reviews,
        "is_reviewed": is_reviewed,
        "my_review": my_review
            }
    return render(request, "ecommerce/item_detail.html", context)


def search(request):
    query = request.GET.get('q')
    items = Item.objects.filter(name__icontains=query)
    reviews = Review.objects.all()

    context = {
        "items": items,
        "reviews": reviews,
        "review_avg": review_avg(),
        'query': query
        }

    return render(request, 'ecommerce/item_list_templates/search_results.html', context)


def item_category(request, category=None):
    if category:
        items = Item.objects.filter(category=category)
    else:
        items = Item.objects.all()

    reviews = Review.objects.all()

    context = {
        "items": items,
        "reviews": reviews,
        "review_avg": review_avg()
        }
    return render(request, 'ecommerce/item_list_templates/item_category_results.html', context)

# ==================== /items views ====================

# ==================== cart handling ====================
@login_required
def cart_list(request):
    cart, created = Cart.objects.get_or_create(user=request.user)
    cart_items = CartItem.objects.filter(cart=cart)
    total_amount = sum(item.quantity * item.price for item in cart_items)

    request.session['cart_items'] = [
        {
            'item_id': item.item.id,
            'item_name': item.item.name,
            'quantity': item.quantity,
            'price': str(item.price) 
        }
        for item in cart_items
    ]

    context = {
        "cart": cart,
        "cart_items": cart_items,
        "total": total_amount
    }
    return render(request, "ecommerce/cart.html", context)


@login_required
def add_to_cart(request, item_id):
    cart, created = Cart.objects.get_or_create(user=request.user)
    item = get_object_or_404(Item, id=item_id)

    cart_item, created = CartItem.objects.get_or_create(
        item=item,
        cart=cart,
        defaults={'quantity': 1, 'price': item.price}
    )

    if not created:
        cart_item.quantity += 1
        cart_item.save()

    return redirect('item-detail', item_id=item_id)


@login_required
def increase_quantity(request, item_id):
    cart = get_object_or_404(Cart, user=request.user)
    cart_item = get_object_or_404(CartItem, cart=cart, item_id=item_id)
    cart_item.quantity += 1
    cart_item.save()
    return redirect('cart-list')

@login_required
def decrease_quantity(request, item_id):
    cart = get_object_or_404(Cart, user=request.user)
    cart_item = get_object_or_404(CartItem, cart=cart, item_id=item_id)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart-list')

@login_required
def remove_item(request, item_id):
    cart = get_object_or_404(Cart, user=request.user)
    cart_item = get_object_or_404(CartItem, cart=cart, item_id=item_id)
    cart_item.delete()
    return redirect('cart-list')
# ==================== /cart handling ====================

# profile view
@login_required
def user_profile(request, user_id):
    user = get_object_or_404(User, id=user_id)
    reviews = Review.objects.filter(user=user)
    orders = Order.objects.filter(user=user)
    orderItems = OrderItem.objects.filter(order__in=orders)

    context = {
        'user': user,
        'reviews': reviews,
        "orders": orders,
        "orderItems": orderItems
    }
    return render(request, "ecommerce/user_profile.html", context)


# ==================== form handling ====================
@login_required
def create_review(request, item_id):
    item = Item.objects.get(id=item_id)
    review_form = ReviewForm()

    if request.method == 'POST':
        rate = request.POST.get('rate') 
        comment = request.POST.get('comment')  

        # Create and save the Review instance
        review = Review(
            item=item,
            user=request.user, 
            rate=rate,
            comment=comment
        )
        review.save()
        return redirect('item-detail', item_id=item_id)

    context = {
        'item': item,
        'form': review_form
    }
    return render(request, "forms/review_form.html", context)


class ReviewUpdateView(UpdateView):
    model = Review
    form_class = ReviewForm
    template_name = 'forms/review_form.html'
    pk_url_kwarg = 'review_id'

    raise_exception = True

    def get_success_url(self):
        return reverse('item-detail', kwargs={'item_id': self.object.item.id})
    
    # def test_func(self):
    #     review = self.get_object()
    #     return review.user == self.request.user


class ReviewDeleteView(DeleteView):
    model = Review
    pk_url_kwarg = 'review_id'
    context_object_name = 'review'

    raise_exception = True

    def get_success_url(self):
        return reverse('item-detail', kwargs={'item_id': self.object.item.id})
    
    # def test_func(self):
    #     review = self.get_object()
    #     return review.user == self.request.user

@login_required
def order_form(request):
    if request.method == 'POST':
        order_form = OrderForm(request.POST)
        if order_form.is_valid():
            cart_items = request.session.get('cart_items')

            if not cart_items:
                return redirect('cart-list')

            # 세션에 Order 및 OrderItems 데이터 저장
            order_data = {
                'user_id': request.user.id,
                'form_data': order_form.cleaned_data,  # OrderForm에서 받은 데이터를 저장
                'items': cart_items  # 장바구니 아이템을 세션에 저장
            }
            request.session['order_data'] = order_data

            return redirect('process_payment')
    else:
        order_form = OrderForm()

    cart_items = request.session.get('cart_items', [])
    total_amount = sum(
        float(item['quantity']) * float(item['price'])
        for item in cart_items
    )

    context = {
        'form': order_form,
        'cart_items': cart_items,
        'total': total_amount
    }

    return render(request, "forms/order_form.html", context)


stripe.api_key = settings.STRIPE_SECRET_KEY

def process_payment(request):
    order_data = request.session.get('order_data')
    if not order_data:
        return redirect('cart-list')

    if request.method == 'POST':
        form = PaymentForm(request.POST)
        if form.is_valid():
            token = request.POST.get('stripeToken')
            try:
                # 결제 처리
                total_amount = sum(
                    float(item['quantity']) * float(item['price'])
                    for item in order_data['items']
                )
                charge = stripe.Charge.create(
                    amount=int(total_amount * 100),  # 센트 단위로 금액 설정
                    currency='usd',
                    description=f"Order by {request.user.email}",
                    source=token,
                )

                # Order 및 OrderItems 데이터베이스에 저장
                order = Order.objects.create(
                    user_id=order_data['user_id'],
                    is_paid=True,
                    paymentId=charge['id'],
                    **order_data['form_data']  # OrderForm에서 받은 데이터 언패킹하여 저장
                )

                for item in order_data['items']:
                    OrderItem.objects.create(
                        order=order,
                        item_id=item['item_id'],
                        price=item['price'],
                        quantity=item['quantity']
                    )

                # 장바구니 비우기 및 세션 데이터 삭제
                user_cart = Cart.objects.get(user=request.user)
                user_cart.cart_items.all().delete()
                del request.session['order_data']

ecommerce/templates/forms/order_form.html
{% extends "ecommerce_base/base.html" %}
{% load static %}

{% block content %}
<h2>Order Form</h2>
{% if cart_items %}
{% for item in cart_items %}
{{ item.item_name }} -&gt; {{ item.quantity }} * {{ item.price }}
<br />
{% endfor %}
<br />
total: {{ total|floatformat:2 }}
{% endif %}

<form method="post">
    {% csrf_token %}

    <label for="id_firstName">First Name:</label><br />
    {{ form.firstName }}
    {% if form.firstName.errors %}
    <div class="error">{{ form.firstName.errors }}</div>
    {% endif %}
    <br />

    <label for="id_lastName">Last Name:</label><br />
    {{ form.lastName }}
    {% if form.lastName.errors %}
    <div class="error">{{ form.lastName.errors }}</div>
    {% endif %}
    <br />

    <label for="id_email">Email:</label><br />
    {{ form.email }}
    {% if form.email.errors %}
    <div class="error">{{ form.email.errors }}</div>
    {% endif %}
    <br />

    <label for="id_address">Address:</label><br />
    {{ form.address }}
    {% if form.address.errors %}
    <div class="error">{{ form.address.errors }}</div>
    {% endif %}
    <br />

    <label for="id_country">Country:</label><br />
    {{ form.country }}
    {% if form.country.errors %}
    <div class="error">{{ form.country.errors }}</div>
    {% endif %}
    <br />

    <label for="id_city">City:</label><br />
    {{ form.city }}
    {% if form.city.errors %}
    <div class="error">{{ form.city.errors }}</div>
    {% endif %}
    <br />

    <label for="id_province">Province:</label><br />
    {{ form.province }}
    {% if form.province.errors %}
    <div class="error">{{ form.province.errors }}</div>
    {% endif %}
    <br />

    <label for="id_postalCode">Postal Code:</label><br />
    {{ form.postalCode }}
    {% if form.postalCode.errors %}
    <div class="error">{{ form.postalCode.errors }}</div>
    {% endif %}
    <br />

    <input type="submit" value="Order" />
</form>
{% endblock content %}

ecommerce/templates/forms/process_payment.html
{% extends "ecommerce_base/base.html" %}
{% load static %}
{% block content %}

<!-- templates/payment_form.html -->
<form action="{% url 'process_payment' %}" method="post" id="payment-form">
    {% csrf_token %}
    {{ form.as_p }}

    <!-- Stripe Elements가 카드 정보를 수집합니다. -->
    <div id="card-element">

    </div>

    <!-- 카드 오류를 표시할 영역 -->
    <div id="card-errors" role="alert"></div>

    <button type="submit">Pay Now</button>
</form>

<script src="https://js.stripe.com/v3/"></script>
<script>
    var stripe = Stripe('pk_test_51PnoJKLXuXyUTOdP4l2B0TNCaH3WIWdRK0yOXsnGfxfNv1N0UYLWYNytr6CTsJFe5c6bCy7gMU7Kv5o09azlMj7y004OtXrsiz');  // Stripe의 Publishable Key
    var elements = stripe.elements();

    var card = elements.create('card');
    card.mount('#card-element');

    // 폼이 제출되면 Stripe가 처리하도록 설정합니다.
    var form = document.getElementById('payment-form');
    form.addEventListener('submit', function(event) {
        event.preventDefault();

        stripe.createToken(card).then(function(result) {
            if (result.error) {
                // 오류를 #card-errors에 표시합니다.
                var errorElement = document.getElementById('card-errors');
                errorElement.textContent = result.error.message;
            } else {
                // Stripe 토큰을 서버로 전송합니다.
                stripeTokenHandler(result.token);
            }
        });
    });

    function stripeTokenHandler(token) {
        var form = document.getElementById('payment-form');
        var hiddenInput = document.createElement('input');
        hiddenInput.setAttribute('type', 'hidden');
        hiddenInput.setAttribute('name', 'stripeToken');
        hiddenInput.setAttribute('value', token.id);
        form.appendChild(hiddenInput);

        // 폼을 제출합니다.
        form.submit();
    }
</script>
{% endblock content %}

ecommerce/templates/forms/review_form.html
{% extends "ecommerce_base/base.html" %}
{% load static %}

{% block css %}
<link
rel="stylesheet"
type="text/css"
href="{% static 'ecommerce/styles/review_form.css' %}"
/>
{% endblock css %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {% if form.rate.value != 1 %}
        <div class="star-rating">
            {% for i in "12345" %}
            {% if forloop.counter <= review.rate %}
            <span data-value="{{i}}" class="selected">&#9733;</span>
            {% else %}
            <span data-value="{{i}}">&#9733;</span>
            {% endif %}
        {% endfor %}
        </div>
        <p id="rating-value">Rating: {{form.rate.value}}</p>
        <div class="rate-container">
            {{ form.rate }}<br />
        </div>
    {% else %}
        <div class="star-rating">
            <span data-value="1" class="selected">&#9733;</span>
            <span data-value="2">&#9733;</span>
            <span data-value="3">&#9733;</span>
            <span data-value="4">&#9733;</span>
            <span data-value="5">&#9733;</span>
        </div>
        <p id="rating-value">Rating: 1</p>
        <div class="rate-container">
            {{ form.rate }}<br />
        </div>
    {% endif %}
    <div class="content-container">
        Content: <br />
        {{ form.comment }}
    </div>
    <button type="submit">Submit</button>
</form>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        const stars = document.querySelectorAll('.star-rating span');
        const ratingValue = document.getElementById('rating-value');
        const rateInput = document.querySelector('[name="rate"]'); 
    
        stars.forEach((star, index) => {
            star.addEventListener('mouseover', () => {
                stars.forEach((s, i) => {
                    if (i <= index) {
                        s.classList.add('hover');
                    } else {
                        s.classList.remove('hover');
                    }
                });
            });
    
            star.addEventListener('mouseout', () => {
                stars.forEach((s) => {
                    s.classList.remove('hover');
                });
            });
    
            star.addEventListener('click', () => {
                // 선택된 별까지 모두 색상을 변경
                stars.forEach((s) => {
                    s.classList.remove('selected');
                });
                star.classList.add('selected');
                let selected = false;
                stars.forEach((s) => {
                    if (selected) {
                        s.classList.remove('selected');
                    } else {
                        s.classList.add('selected');
                    }
                    if (s === star) selected = true;
                });
    
                // 선택된 평점 값을 표시하고 form의 rate 필드에 설정
                const rating = star.getAttribute('data-value');
                ratingValue.textContent = `Rating: ${rating}`;
                rateInput.value = rating; // form의 rate 필드 값 설정
            });
        });
    });
</script>
{% endblock content %}